[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "formula1-race-results-web-app"
version = "0.1.0"
description = "Add your description here"
authors = [{name = "KrisKulbych", email = "k.kulbych@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask-caching>=2.3.1",
    "flask>=3.1.1",
    "pydantic-settings>=2.9.1",
    "formula1-race-analysis>=2.0.1",
]

[dependency-groups]
dev = [
    "pytest-cov>=6.2.1",
    "pytest>=8.4.0",
]
lint = [
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "ruff>=0.11.13",
]
[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.workspace]
exclude = ["tests/*"]

[tool.pytest.ini_options]
addopts = "-v --cov=. --cov-fail-under=90"
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]
ignore = ["F401", "COM812", "ISC001", "D", "S", "TRY", "T", "EM", "DTZ", "G"]

[tool.ruff.format]
indent-style = "space"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_no_return = true
show_error_context = true
show_column_numbers = true
warn_unused_configs = true

[tool.flake8]
ignore = ["COM812", "ISC001"]

[tool.setuptools]
include-package-data = true
py-modules = ["f1_web_app"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.exclude-package-data]
"tests" = ["*"]

[[tool.uv.index]]
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
default = true

[[tool.uv.index]]
url = "https://pypi.org/simple/"

[project.scripts]
f1_web_app= "f1_web_app:f1_web_app"
