name: formula1-race-results-web-api-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install the project
        run: uv sync --all-extras --group dev --group lint --index-strategy unsafe-best-match
      - name: Run Ruff Linter
        run: uv run ruff check
      - name: Run Ruff Formatter
        run: uv run ruff format
      - name: Run mypy
        run: uv run mypy .
      - name: Run tests with Pytest
        run: |
          uv run pytest -v --cov=. --cov-fail-under=90
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
